/* Generated by Yosys 0.38+4 (git sha1 ac0fb2e30, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "inverter.v:1.1-3.10" *)
module inverter(a, b);
  (* src = "inverter.v:1.23-1.24" *)
  input a;
  wire a;
  (* src = "inverter.v:1.33-1.34" *)
  output b;
  wire b;
  INV_X1 _0_ (
    .A(a),
    .ZN(b)
  );
endmodule
